"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Download, Loader2 } from "lucide-react";
import { toast } from "sonner";

interface DownloadPDFButtonProps {
    sessionId: string;
    jobTitle?: string;
    company?: string;
    overallScore: number;
    strengths: string[];
    weaknesses: string[];
    questionFeedbacks: any[];
}

export function DownloadPDFButton({ sessionId, jobTitle, company, overallScore, strengths, weaknesses, questionFeedbacks }: DownloadPDFButtonProps) {
    const [loading, setLoading] = useState(false);

    const handleDownload = async () => {
        setLoading(true);
        try {
            // Generate PDF-like content as a well-formatted HTML and trigger print
            const printWindow = window.open('', '_blank');
            if (!printWindow) {
                toast.error("Please allow pop-ups to download PDF");
                return;
            }

            const questionsHtml = questionFeedbacks.map((qf: any, i: number) => `
                <div style="margin-bottom: 20px; padding: 16px; border: 1px solid #e2e8f0; border-radius: 12px;">
                    <div style="display: flex; justify-content: space-between; margin-bottom: 8px;">
                        <strong>Question ${i + 1}</strong>
                        <span style="color: ${qf.score >= 75 ? '#059669' : qf.score >= 55 ? '#d97706' : '#dc2626'}; font-weight: bold;">${qf.score}/100</span>
                    </div>
                    <p style="color: #475569; font-style: italic; margin: 8px 0;">"${qf.question}"</p>
                    <p style="color: #64748b; font-size: 13px; margin: 8px 0;"><strong>Your Answer:</strong> "${qf.answer}"</p>
                    <p style="color: #334155; font-size: 13px; margin: 8px 0;"><strong>AI Analysis:</strong> ${qf.ai_commentary}</p>
                    <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 8px; margin-top: 8px;">
                        <div style="background: #f0fdf4; padding: 8px; border-radius: 8px; font-size: 12px;">
                            <strong style="color: #059669;">✓ Good:</strong> ${qf.what_was_good}
                        </div>
                        <div style="background: #fffbeb; padding: 8px; border-radius: 8px; font-size: 12px;">
                            <strong style="color: #d97706;">→ Improve:</strong> ${qf.what_to_improve}
                        </div>
                    </div>
                </div>
            `).join('');

            printWindow.document.write(`
                <!DOCTYPE html>
                <html>
                <head>
                    <title>Interview Feedback Report - ${jobTitle || 'Session'}</title>
                    <style>
                        * { box-sizing: border-box; margin: 0; padding: 0; }
                        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; padding: 40px; color: #1e293b; max-width: 800px; margin: 0 auto; }
                        h1 { font-size: 24px; margin-bottom: 4px; }
                        h2 { font-size: 18px; margin: 24px 0 12px; color: #334155; }
                        .header { text-align: center; border-bottom: 2px solid #e2e8f0; padding-bottom: 20px; margin-bottom: 24px; }
                        .score-big { font-size: 48px; font-weight: 900; color: #3b82f6; margin: 12px 0; }
                        .meta { color: #64748b; font-size: 14px; }
                        .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 24px; }
                        .card { padding: 16px; border-radius: 12px; }
                        .card-green { background: #f0fdf4; border: 1px solid #bbf7d0; }
                        .card-amber { background: #fffbeb; border: 1px solid #fde68a; }
                        li { margin: 6px 0; font-size: 13px; color: #475569; }
                        .footer { text-align: center; margin-top: 32px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #94a3b8; }
                        @media print { body { padding: 20px; } }
                    </style>
                </head>
                <body>
                    <div class="header">
                        <h1>📋 Interview Feedback Report</h1>
                        <p class="meta">${jobTitle || 'Interview Session'}${company ? ` at ${company}` : ''}</p>
                        <div class="score-big">${overallScore}/100</div>
                        <p class="meta">Generated by Intervio AI • ${new Date().toLocaleDateString()}</p>
                    </div>
                    <div class="grid">
                        <div class="card card-green">
                            <h2 style="margin-top:0; color: #059669;">✅ Strengths</h2>
                            <ul style="padding-left: 16px;">
                                ${strengths.map(s => `<li>${s}</li>`).join('')}
                            </ul>
                        </div>
                        <div class="card card-amber">
                            <h2 style="margin-top:0; color: #d97706;">⚠️ Areas to Improve</h2>
                            <ul style="padding-left: 16px;">
                                ${weaknesses.map(w => `<li>${w}</li>`).join('')}
                            </ul>
                        </div>
                    </div>
                    <h2>📝 Question-by-Question Analysis</h2>
                    ${questionsHtml}
                    <div class="footer">
                        <p>Intervio AI — Your Personal Intervio | intervioai.com</p>
                    </div>
                </body>
                </html>
            `);

            printWindow.document.close();
            setTimeout(() => {
                printWindow.print();
            }, 500);

            toast.success("PDF ready for download!");
        } catch {
            toast.error("Failed to generate PDF");
        } finally {
            setLoading(false);
        }
    };

    return (
        <Button
            onClick={handleDownload}
            disabled={loading}
            variant="outline"
            className="bg-transparent border-white/20 text-white hover:bg-white/10 hover:text-white"
        >
            {loading ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : <Download className="h-4 w-4 mr-2" />}
            Download PDF
        </Button>
    );
}
